language: python

jobs:
  include:
    - stage: lint
      script: flake8 src/drf_yasg2 testproj tests setup.py
      install:
        - pip install -r requirements/lint.txt

    - stage: unittest
      script: tox
      python:
        - 3.6
        - 3.7
        - 3.8
      env:
        - TOXENV=stable
        - TOXENV=latest
      install:
        - pip install -r requirements/test.txt

    - stage: check-docs
      script: twine check .tox/dist/*
      install:
        - pip install -r requirements/docs.txt

    # Check readthedocs will be able to build the docs after publishing
    - stage: test-docs
      script: sphinx-build -WnEa -b html docs docs/_build/html
      install:
        - pip install -r requirements/docs.txt

  allow_failures:
    - env: TOXENV=latest

before_deploy: "pip install -r requirements/publish.txt"

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: joellefkowitz
  password:
    secure: fbaBrbBl6mJf54iV2LR/wskFZRGn1ftlgt+BCCGsdF2eDrASnQaszS/IM4PXd4bsUalAPcxcbGC0lEAqiDgZneKlSYvHps1oy6ypymq7JLHKW/iQ3bBeXvT2QEaUgg5LqjX2CIlhSgiY2mVa6gQt1BwlutJatM3sJ6yvBQu+3vVWpwWohfTqjPmt1FdR9WWz5/sviDFyHYnGSRmgQUkcyfnKHZ4/UtEiLynVC1RVNzb+aAOCp2M2lW+A2SBiKMISzbkvgL/pO9f8ceHInUhY+oZJ/wzMa1hyF+Dlo7ut3LywFNrFdheP5r/1lTusR5UYXKncsiCLCyRujal8hOAnUaHkP+XGm+QLULKOGG2qkxmasO7lRXSbYgQGEGoKQNsiwjqJN3AbofIL1FIw/2IYFia/bkvhZCyBLUAHoCJ0BgNF/kvYBDzBDR2b6r8GjG2OREL+tkgAAsHauRgYKfkP738Qqj8UEnQ+Xrtnm+zOw86AuYD4xx3DHS2qAzsnhEs4nVp6WvLSB4PqOzzLZmG73zQZgKTTGIs7kgtnIZBR+3gIQCFIUAaeV9rzNmED0eKt8qLtC4gXFLx5aqzM2hOnuuKII+Ueiz8ZPbjFXrE7VmpCr0KfJaxu4UcqgSjJY5OI9f3EGJsJIC7O1fkrNCNPH0UUTZM0fM9OlxUNPs8qp1I=
  on:
    branch: master
    tags: true
