language: python
python:
- '3.6'
- '3.7'
- '3.8'
dist: xenial
cache: pip
matrix:
  include:
  - python: '3.6'
    env: TOXENV=docs
  - python: '3.7'
    env: TOXENV=djmaster
  - python: '3.7'
    env: TOXENV=lint
  - stage: publish
    python: '3.6'
    before_script:
    - pip install setuptools-scm
    script: skip
    env: PYPI_DEPLOY=true
    deploy:
      provider: pypi
      user: joellefkowitz
      password:
        secure: fbaBrbBl6mJf54iV2LR/wskFZRGn1ftlgt+BCCGsdF2eDrASnQaszS/IM4PXd4bsUalAPcxcbGC0lEAqiDgZneKlSYvHps1oy6ypymq7JLHKW/iQ3bBeXvT2QEaUgg5LqjX2CIlhSgiY2mVa6gQt1BwlutJatM3sJ6yvBQu+3vVWpwWohfTqjPmt1FdR9WWz5/sviDFyHYnGSRmgQUkcyfnKHZ4/UtEiLynVC1RVNzb+aAOCp2M2lW+A2SBiKMISzbkvgL/pO9f8ceHInUhY+oZJ/wzMa1hyF+Dlo7ut3LywFNrFdheP5r/1lTusR5UYXKncsiCLCyRujal8hOAnUaHkP+XGm+QLULKOGG2qkxmasO7lRXSbYgQGEGoKQNsiwjqJN3AbofIL1FIw/2IYFia/bkvhZCyBLUAHoCJ0BgNF/kvYBDzBDR2b6r8GjG2OREL+tkgAAsHauRgYKfkP738Qqj8UEnQ+Xrtnm+zOw86AuYD4xx3DHS2qAzsnhEs4nVp6WvLSB4PqOzzLZmG73zQZgKTTGIs7kgtnIZBR+3gIQCFIUAaeV9rzNmED0eKt8qLtC4gXFLx5aqzM2hOnuuKII+Ueiz8ZPbjFXrE7VmpCr0KfJaxu4UcqgSjJY5OI9f3EGJsJIC7O1fkrNCNPH0UUTZM0fM9OlxUNPs8qp1I=

      on:
        tags: true
      distributions: sdist bdist_wheel
  allow_failures:
  - env: TOXENV=djmaster
  fast_finish: true
install:
- python -m pip install -U pip setuptools
- pip install -r requirements/ci.txt
before_script:
- coverage erase
script:
- tox
after_success:
- |
  if [[ -z "$TOXENV" && -z "$PYPI_DEPLOY" ]]; then
    coverage combine || true
    coverage report
    codecov
  fi
stages:
- test
- name: publish
  if: tag IS present
notifications:
  email:
    on_success: always
    on_failure: always
